-- MySQL Script generated by MySQL Workbench
-- 11/10/15 02:42:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Exp_sys
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Exp_sys` ;

-- -----------------------------------------------------
-- Schema Exp_sys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Exp_sys` ;
USE `Exp_sys` ;

-- -----------------------------------------------------
-- Table `Exp_sys`.`diagnoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`diagnoses` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`diagnoses` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`anamnesis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`anamnesis` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`anamnesis` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` TEXT NULL COMMENT '',
  `complains` TEXT NULL COMMENT '',
  `description_sickness` TEXT NULL COMMENT '',
  `description_life` TEXT NULL COMMENT '',
  `Virus_deseases` TEXT NULL COMMENT '',
  `description_allergic` TEXT NULL COMMENT '',
  `State` TINYINT(1) NULL COMMENT '',
  `physique` TEXT NULL COMMENT '',
  `diet` TEXT NULL COMMENT '',
  `skin` TEXT NULL COMMENT '',
  `edema` TEXT NULL COMMENT '',
  `lymph nodes` TEXT NULL COMMENT '',
  `temperature` TEXT NULL COMMENT '',
  `respRate` TEXT NULL COMMENT '',
  `ChestVol` TEXT NULL COMMENT '',
  `percurative` TEXT NULL COMMENT '',
  `breathing` TEXT NULL COMMENT '',
  `heart_borders` TEXT NULL COMMENT '',
  `heart_tones` TEXT NULL COMMENT '',
  `artpressure` TEXT NULL COMMENT '',
  `heartRate` TEXT NULL COMMENT '',
  `pulse` TEXT NULL COMMENT '',
  `stomach` TEXT NULL COMMENT '',
  `liver` TEXT NULL COMMENT '',
  `Pastern` TEXT NULL COMMENT '',
  `stool` TEXT NULL COMMENT '',
  `urine` TEXT NULL COMMENT '',
  `PreDiagnosis_id` INT NULL COMMENT '',
  `Conclusion_compl` TEXT NULL COMMENT '',
  `conclusion_anamnesis` TEXT NULL COMMENT '',
  `research_plan` TEXT NULL COMMENT '',
  `treatment_plan` TEXT NULL COMMENT '',
  `disability` TEXT NULL COMMENT '',
  `doctor` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `diagnosis1_id_idx` (`PreDiagnosis_id` ASC)  COMMENT '',
  CONSTRAINT `preDiagnosis_id`
    FOREIGN KEY (`PreDiagnosis_id`)
    REFERENCES `Exp_sys`.`diagnoses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`Adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`Adress` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`Adress` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `region` TEXT NULL COMMENT '',
  `district` TEXT NULL COMMENT '',
  `city` TEXT NULL COMMENT '',
  `street` TEXT NULL COMMENT '',
  `house` TEXT NULL COMMENT '',
  `housing` TEXT NULL COMMENT '',
  `appartement` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`patient_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`patient_info` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`patient_info` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Sex` TINYINT(1) NULL COMMENT '',
  `diagnoses_id` INT NULL COMMENT '',
  `SNILS` INT NULL COMMENT '',
  `INN` INT NULL COMMENT '',
  `Passport_data` VARCHAR(500) NULL COMMENT '',
  `anamnesis_id` INT NULL COMMENT '',
  `FIO` TEXT NULL COMMENT '',
  `Insurance_number` TEXT NULL COMMENT '',
  `OGRN` TEXT NULL COMMENT '',
  `Insurance_firm` TEXT NULL COMMENT '',
  `card_number` TEXT NULL COMMENT '',
  `benefit_number` TEXT NULL COMMENT '',
  `adress_current_id` INT NULL COMMENT '',
  `adress_const_id` INT NULL COMMENT '',
  `birth_date` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `diagnosis_idx` (`diagnoses_id` ASC)  COMMENT '',
  INDEX `anamnesis_id_idx` (`anamnesis_id` ASC)  COMMENT '',
  INDEX `adress_curr_fk_idx` (`adress_current_id` ASC)  COMMENT '',
  INDEX `adress_const_fk_idx` (`adress_const_id` ASC)  COMMENT '',
  CONSTRAINT `diagnosis_fk`
    FOREIGN KEY (`diagnoses_id`)
    REFERENCES `Exp_sys`.`diagnoses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `anamnesis_id`
    FOREIGN KEY (`anamnesis_id`)
    REFERENCES `Exp_sys`.`anamnesis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `adress_curr_fk`
    FOREIGN KEY (`adress_current_id`)
    REFERENCES `Exp_sys`.`Adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `adress_const_fk`
    FOREIGN KEY (`adress_const_id`)
    REFERENCES `Exp_sys`.`Adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`dye_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`dye_type` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`dye_type` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`scope_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`scope_type` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`scope_type` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL DEFAULT 'Default' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`entry` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`entry` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `about` VARCHAR(1000) NULL COMMENT '',
  `picture_ref` VARCHAR(100) NOT NULL COMMENT '',
  `patient_info_id` INT NULL COMMENT '',
  `scope_type_id` INT NULL COMMENT '',
  `dye_type_id` INT NULL COMMENT '',
  `zoom` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `patient_idx` (`patient_info_id` ASC)  COMMENT '',
  INDEX `dye_idx` (`dye_type_id` ASC)  COMMENT '',
  INDEX `scope_idx` (`scope_type_id` ASC)  COMMENT '',
  CONSTRAINT `patient_fk`
    FOREIGN KEY (`patient_info_id`)
    REFERENCES `Exp_sys`.`patient_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dye_fk`
    FOREIGN KEY (`dye_type_id`)
    REFERENCES `Exp_sys`.`dye_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scope_fk`
    FOREIGN KEY (`scope_type_id`)
    REFERENCES `Exp_sys`.`scope_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Exp_sys`.`cond_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`cond_area` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`cond_area` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `description` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`TRadius`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`TRadius` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`TRadius` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `MaxRadius` FLOAT NULL COMMENT '',
  `MinRadius` FLOAT NULL COMMENT '',
  `AverageRadius` FLOAT NULL COMMENT '',
  `MeanSquareRadius` FLOAT NULL COMMENT '',
  `MaxRadiusPointX` POINT NULL COMMENT '',
  `MinRadiusPointX` POINT NULL COMMENT '',
  `InertiaMoment` FLOAT NULL COMMENT '',
  `RelInertiaMoment` FLOAT NULL COMMENT '',
  `Valid` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `TRadiuscol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`TFere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`TFere` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`TFere` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `MinDiametr` FLOAT NULL COMMENT '',
  `AngleMin` INT NULL COMMENT '',
  `CoupleMin1` POINT NULL COMMENT '',
  `CoupleMin2` POINT NULL COMMENT '',
  `MaxDiametr` FLOAT NULL COMMENT '',
  `AngleMax` INT NULL COMMENT '',
  `CoupleMax1` POINT NULL COMMENT '',
  `CoupleMax2` POINT NULL COMMENT '',
  `AverageDiametr` FLOAT NULL COMMENT '',
  `MeanSquareDiametr` FLOAT NULL COMMENT '',
  `Valid` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`morph_tthing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`morph_tthing` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`morph_tthing` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Min` POINT NULL COMMENT '',
  `Max` POINT NULL COMMENT '',
  `Spots` INT NULL COMMENT '',
  `SpotsSquare` INT NULL COMMENT '',
  `Start` POINT NULL COMMENT '',
  `ExtCircuit8Len` INT NULL COMMENT '',
  `ExtCircuit4Len` INT NULL COMMENT '',
  `ExtPerimetr` INT NULL COMMENT '',
  `IntCircuit8Len` INT NULL COMMENT '',
  `IntCircuit4Len` INT NULL COMMENT '',
  `IntPerimetr` INT NULL COMMENT '',
  `Square` INT NULL COMMENT '',
  `Fulness` FLOAT NULL COMMENT '',
  `ShapeFactor` FLOAT NULL COMMENT '',
  `Center` POINT NULL COMMENT '',
  `TRadius_id` INT NULL COMMENT '',
  `TFere_id` INT NULL COMMENT '',
  `ExtCircuitPoints` BLOB NULL COMMENT '',
  `IntCircuitPoints` BLOB NULL COMMENT '',
  `AllPoints` BLOB NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Tradius_idx` (`TRadius_id` ASC)  COMMENT '',
  INDEX `Tfere_idx` (`TFere_id` ASC)  COMMENT '',
  CONSTRAINT `Tradius_fk`
    FOREIGN KEY (`TRadius_id`)
    REFERENCES `Exp_sys`.`TRadius` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tfere_fk`
    FOREIGN KEY (`TFere_id`)
    REFERENCES `Exp_sys`.`TFere` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`mark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`mark` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`mark` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `entry_id` INT NOT NULL COMMENT '',
  `form` ENUM('rectangle', 'ellipse', 'polygon', 'arrow', 'nofigure') NULL DEFAULT NULL COMMENT '',
  `thickness` INT NULL COMMENT '',
  `cond_area_id` INT NULL COMMENT '',
  `name_id` INT NULL COMMENT '',
  `morph_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `entry_fk` (`entry_id` ASC)  COMMENT '',
  INDEX `diagnosis_idx` (`cond_area_id` ASC)  COMMENT '',
  INDEX `Morph_idx` (`morph_id` ASC)  COMMENT '',
  CONSTRAINT `entry_fk`
    FOREIGN KEY (`entry_id`)
    REFERENCES `Exp_sys`.`entry` (`id`),
  CONSTRAINT `cond_area_fk`
    FOREIGN KEY (`cond_area_id`)
    REFERENCES `Exp_sys`.`cond_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `morph_fk`
    FOREIGN KEY (`morph_id`)
    REFERENCES `Exp_sys`.`morph_tthing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Exp_sys`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`Users` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(45) NULL COMMENT '',
  `FirstName` VARCHAR(45) NULL COMMENT '',
  `LastName` VARCHAR(45) NULL COMMENT '',
  `type` INT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`journal` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`journal` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tableName` VARCHAR(45) NULL COMMENT '',
  `colName` VARCHAR(45) NULL COMMENT '',
  `rowId` INT NULL COMMENT '',
  `newValue` VARCHAR(1000) NULL COMMENT '',
  `Users_id` INT NULL COMMENT '',
  `Date` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `UserId_idx` (`Users_id` ASC)  COMMENT '',
  CONSTRAINT `UserId_fk`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Exp_sys`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`mark_points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`mark_points` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`mark_points` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `point` POINT NULL COMMENT '',
  `mark_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `mark_id_idx` (`mark_id` ASC)  COMMENT '',
  CONSTRAINT `mark_id_fk`
    FOREIGN KEY (`mark_id`)
    REFERENCES `Exp_sys`.`mark` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exp_sys`.`Mark_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exp_sys`.`Mark_name` ;

CREATE TABLE IF NOT EXISTS `Exp_sys`.`Mark_name` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `color` INT NULL COMMENT '',
  `ParentId` INT NOT NULL DEFAULT -1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

USE `Exp_sys` ;

-- -----------------------------------------------------
-- procedure f_entryid_patientid
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`f_entryid_patientid`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `f_entryid_patientid` (in pat_id int)
BEGIN
		SELECT id FROM entry WHERE patient_info_id=(SELECT id  FROM patient_info WHERE id=pat_id);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sh_m_fullname
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`sh_m_fullname`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `sh_m_fullname` (in markid int, out markfeat varchar(100), out marktype varchar(100), out markname varchar(100) )
BEGIN
	SELECT name FROM mark_struct_type where id=(SELECT mark_struct_type_id FROM mark_struct_feature WHERE id=(SELECT mark_struct_feature_id FROM mark_name where id=markid)) INTO markfeat;
    SELECT name FROM mark_struct_feature WHERE id=(SELECT mark_struct_feature_id FROM mark_name where id=markid) INTO marktype;
    SELECT name FROM mark_name where id=markid INTO markname;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sh_m_type
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`sh_m_type`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `sh_m_type` ()
BEGIN

END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Anamnesys_pg1
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`Fill_Anamnesys_pg1`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `Fill_Anamnesys_pg1` (in dateIn text, in complIn text, in SickIn text, in LifeIn text, in deseasIn text, in allergIn text)
BEGIN
If (SELECT COUNT(*) FROM anamnesis)=0 then
INSERT INTO `anamnesis` (`id`, `date`, `complains`, `description_sickness`, `description_life`, `Virus_deseases`, `description_allergic`) VALUES ('0', dateIn, complIn, SickIn, LifeIn, deseasIn, allergIn);
else 
INSERT INTO `anamnesis` (`date`, `complains`, `description_sickness`, `description_life`, `Virus_deseases`, `description_allergic`) VALUES (dateIn, complIn, SickIn, LifeIn, deseasIn, allergIn);
end if;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Anamnesys_pg2
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`Fill_Anamnesys_pg2`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `Fill_Anamnesys_pg2` (in StateIn bool, in  PhysIn text, in  DietIn text, in  skinIn text, in  edemIn text, in  lymphIn text, in  tempIn text, in  respIn text, in  ChestIn text, in  PercurIn text, in  BreathIn text)
BEGIN
declare r int;
set r =(Select LAST_INSERT_ID());
update anamnesis
	set 
    `State`= StateIn,
    `physique` = PhysIn,
    `diet`= DietIn,
    `skin`= skinIn,
    `edema`= edemIn,
    `lymph nodes` = lymphIn,
    `temperature` = tempIn,
    `respRate` = respIn,
    `ChestVol` = ChestIn,
    `percurative` = PercurIn,
    `breathing` = BreathIn
    where id = r;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Anamnesys_pg3
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`Fill_Anamnesys_pg3`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `Fill_Anamnesys_pg3` (in HeartBorIn text, in  HeartTonIn text, in  ArtPresIn text, in  HeartRateIn text, in  PulseIn text, in  StomachIn text, in  liverIn text, in  PasternIn text, in  stoolIn text, in  urineIn text)
BEGIN
declare r int;
set r =(Select LAST_INSERT_ID());
update anamnesis
	set
	`heart_borders` = HeartBorIn,
    `heart_tones` = HeartTonIn,
    `artpressure` =  ArtPresIn,
    `heartRate` = HeartRateIn,
    `pulse` = PulseIn,
    `stomach` = StomachIn,
    `liver` = liverIn,
    `Pastern` = PasternIn,
    `stool` = stoolIn,
    `urine` = urineIn
    where id = r;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Anamnesys_pg4
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`Fill_Anamnesys_pg4`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `Fill_Anamnesys_pg4` (in diagName VARCHAR(100), in  complIn text, in  anamnIn text, in  researchIn text, in  treatmIn text, in  DisabilIn text, in  DoctIn text)
BEGIN
declare r int;
declare PreDiag int;
set r =(LAST_INSERT_ID());
if (SELECT COUNT(id) FROM diagnoses where `name`=diagName)=0 then
call exp_sys.Fill_Diag(diagName,'');
SELECT LAST_INSERT_ID() into PreDiag;
else
SELECT `id` into PreDiag FROM diagnoses where `name`=diagName;
end if;
update anamnesis
	set
	`PreDiagnosis_id` = preDiag,
    `Conclusion_compl` = complIn,
    `conclusion_anamnesis` = anamnIn,
    `research_plan` = researchIn,
    `treatment_plan` = treatmIn,
    `disability` = DisabilIn,
    `doctor` = DoctIn
    where id = r;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Diag
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`Fill_Diag`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `Fill_Diag` (in NameIn varchar(100), in DescriptIn varchar(1000))
BEGIN
If (SELECT COUNT(*) FROM Diagnoses)=0 then
	INSERT INTO `Exp_sys`.`diagnoses` (`id`, `name`, `description`) VALUES (0, NameIn, DescriptIn);
else
	INSERT INTO `Exp_sys`.`diagnoses` (`name`, `description`) VALUES (NameIn, DescriptIn);
end if;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Adress
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`Fill_Adress`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `Fill_Adress` (in inRegion text, in inDistrict text, in inCity text, in inStreet text, in inHouse text, in inHousing text, in inAppartement text)
BEGIN
If (SELECT COUNT(*) FROM Adress)=0 then
	INSERT INTO `adress` (`id`, `region`, `district`, `city`, `street`, `house`, `housing`, `appartement`) VALUES ('0', inRegion, inDistrict, inCity, inStreet, inHouse, inHousing, inAppartement);
else
	INSERT INTO `adress` (`region`, `district`, `city`, `street`, `house`, `housing`, `appartement`) VALUES (inRegion, inDistrict, inCity, inStreet, inHouse, inHousing, inAppartement);
end if;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_patient_info
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`Fill_patient_info`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `Fill_patient_info` (in sexIn bool, in diagName VARCHAR(100), in SNILSIn int, in INNin int, in passportIn VARCHAR(500), in anamIn int,in FIOin text, in insurnumIn text, in OGRNIn text, in InsurIn text, in cardNoIn text, in BenefinNumIn text, in birthDateIn date,
in a1 text, in a2 text, in a3 text, in a4 text, in a5 text, in a6 text, in a7 text, in b1 text, in b2 text, in b3 text, in b4 text, in b5 text, in b6 text, in b7 text)
BEGIN
declare adressCurrIn, AdressConstIn int;
declare dnum int;
if (SELECT COUNT(id) FROM diagnoses where `name`=diagName)=0 then
call exp_sys.Fill_Diag(diagName,'');
SELECT LAST_INSERT_ID() into dnum;
else
SELECT `id` into dnum FROM diagnoses where `name`=diagName;
end if;
if (Select COUNT(id) FROM anamnesis where id=anamIn)=0 then
set anamIn=Null;
else set anamIn=anamIn;
end if;

call exp_sys.Fill_adress(a1, a2, a3, a4, a5, a6, a7);
SELECT LAST_INSERT_ID() into AdressConstIn;
call exp_sys.Fill_adress(b1, b2, b3, b4, b5, b6, b7);
SELECT LAST_INSERT_ID() into AdressCurrIn;
If (SELECT COUNT(*) FROM patient_info)=0 then
	INSERT INTO `patient_info` (`id`, `Sex`, `diagnoses_id`, `SNILS`, `INN`, `Passport_data`, `anamnesis_id`, `FIO`, `Insurance_number`, `OGRN`, `Insurance_firm`, `card_number`, `benefit_number`, `adress_current_id`, `adress_const_id`, `birth_date`) VALUES ('0', sexIn, dnum, SNILSIn, INNin, passportIn, anamIn, FIOin, insurnumIn, OGRNIn, InsurIn, cardNoIn, BenefinNumIn, adressCurrIn, AdressConstIn, birthDateIn);
else
	INSERT INTO `patient_info` (`Sex`, `diagnoses_id`, `SNILS`, `INN`, `Passport_data`, `anamnesis_id`, `FIO`, `Insurance_number`, `OGRN`, `Insurance_firm`, `card_number`, `benefit_number`, `adress_current_id`, `adress_const_id`, `birth_date`) VALUES (sexIn, dnum, SNILSIn, INNin, passportIn, anamIn, FIOin, insurnumIn, OGRNIn, InsurIn, cardNoIn, BenefinNumIn, adressCurrIn, AdressConstIn, birthDateIn);
end if;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_entry
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`Fill_entry`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `Fill_entry` (in NameIn VARCHAR(100), in descriptIn VARCHAR(1000), in pictLinkIn VARCHAR(100), in patientidIn int)
BEGIN
if (Select COUNT(id) FROM patient_info where id=patientidIn)=0 then
set patientidIn=Null;
else set patientidIn=patientidIn;
end if;
	If (SELECT COUNT(*) FROM Adress)=0 then
	INSERT INTO `entry` (`id`, `name`, `about`, `picture_ref`, `patient_info_id`) VALUES ('0', NameIn, descriptIn, pictLinkIn, patientidIn);
else
	INSERT INTO `entry` (`name`, `about`, `picture_ref`, `patient_info_id`) VALUES (NameIn, descriptIn, pictLinkIn, patientidIn);
end if;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure View_Anamnesis
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`View_Anamnesis`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `View_Anamnesis` ()
BEGIN
declare length int default (SELECT COUNT(*) FROM anamnesis);
declare n int default 0;
declare p29 VARCHAR(100); 
declare p1, p2, p3, p4, p5, p6, p7, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, p26, p27, p28, p30, p31, p32, p33, p34, p35 text;
declare p8 TINYINT(1);
declare iddiag int;
CREATE TABLE IF NOT EXISTS `temp`
(
  `id` INT,
  `date` TEXT,
  `complains` TEXT,
  `description_sickness` TEXT,
  `description_life` TEXT,
  `Virus_deseases` TEXT,
  `description_allergic` TEXT,
  `State` TINYINT(1),
  `physique` TEXT,
  `diet` TEXT,
  `skin` TEXT,
  `edema` TEXT,
  `lymph nodes` TEXT,
  `temperature` TEXT,
  `respRate` TEXT,
  `ChestVol` TEXT,
  `percurative` TEXT,
  `breathing` TEXT,
  `heart_borders` TEXT,
  `heart_tones` TEXT,
  `artpressure` TEXT,
  `heartRate` TEXT,
  `pulse` TEXT,
  `stomach` TEXT,
  `liver` TEXT,
  `Pastern` TEXT,
  `stool` TEXT,
  `urine` TEXT,
  `PreDiagnosis_id` TEXT,
  `Conclusion_compl` TEXT,
  `conclusion_anamnesis` TEXT,
  `research_plan` TEXT,
  `treatment_plan` TEXT,
  `disability` TEXT,
  `doctor` TEXT
 );
loop1:while length >0
 Do
	SET length=length-1;
    SET n=n+1;
    SELECT `id`, `date`, `complains`, `description_sickness`, `description_life`, `Virus_deseases`, `description_allergic`, `State`, `physique`, `diet`, `skin`, `edema`, `lymph nodes`, `temperature`, `respRate`, `ChestVol`, `percurative`, `breathing`, `heart_borders`, `heart_tones`, `artpressure`, `heartRate`, `pulse`, `stomach`, `liver`, `Pastern`, `stool`, `urine`, `Conclusion_compl`, `conclusion_anamnesis`, `research_plan`, `treatment_plan`, `disability`, `doctor`
    into p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, p26, p27, p28, p30, p31, p32, p33, p34, p35  from anamnesis where `id`=n;
	Select `PreDiagnosis_id` into iddiag from anamnesis where `id`=n;
    Select `name` into p29 from diagnoses where `id`=iddiag;
    insert into temp values (p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, p26, p27, p28, p29, p30, p31, p32, p33, p34, p35);
end while;
SELECT * FROM  temp;
 DROP TABLE temp;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure View_Patient_info
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`View_Patient_info`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `View_Patient_info` ()
BEGIN

declare length int default (SELECT COUNT(*) FROM patient_info);
declare n int default 0;
declare p1, p5, p6, p9 int;
declare p2 TINYINT(1);
declare p8 varchar(1000);
declare pf DATE;
declare p4, p10, p11, p12, p13, p14, p15 text;
declare iddiag, adresscur, adressconst, anamn int;
declare a1, a2, a3, a4, a5, a6, a7, b1, b2, b3, b4, b5, b6, b7 text; 
CREATE temporary TABLE IF NOT EXISTS `temp`
(
   `id` INT ,
  `Sex` TINYINT(1),
  `diagnoses_id` text,
  `SNILS` INT,
  `INN` INT,
  `Passport_data` VARCHAR(500),
  `anamnesis_id` int,
  `FIO` TEXT,
  `Insurance_number` TEXT,
  `OGRN` TEXT,
  `Insurance_firm` TEXT,
  `card_number` TEXT,
  `benefit_number` TEXT,
  `acur_obl` text ,
  `acur_ray` text,
  `acur_nas` text,
  `acur_ul` text,
  `acur_dom` text,
  `acur_cor` text,
  `acur_kv` text,
  `aconst_obl` text ,
  `aconst_ray` text,
  `aconst_nas` text,
  `aconst_ul` text,
  `aconst_dom` text,
  `aconst_cor` text,
  `aconst_kv` text,
  `birth_date` DATE
);
loop1:while length >0
 Do
	SET length=length-1;
    SET n=n+1;
	Select `id`, `Sex`, `SNILS`, `INN`, `Passport_data`, `anamnesis_id`,`FIO`, `Insurance_number`, `OGRN`, `Insurance_firm`, `card_number`, `benefit_number`, `birth_date`
    into p1, p2, p5, p6, p8, p9, p10, p11, p12, p13, p14, p15, pf from patient_info where id=`n`;
    Select `diagnoses_id` into iddiag from patient_info where `id`=n;
	Select `adress_current_id` into adresscur from patient_info where `id`=n; 
	Select `adress_const_id` into adressconst from patient_info where `id`=n;
    select `name` into p4 from diagnoses where `id`=iddiag;
    select `region`,`district`,`city`,`street`,`house`,`housing`,`appartement` into a1, a2, a3, a4, a5, a6, a7 from Adress where `id`=adresscur;
    select `region`,`district`,`city`,`street`,`house`,`housing`,`appartement` into b1, b2, b3, b4, b5, b6, b7 from Adress where `id`=adressconst;
	insert into temp values (p1, p2, p4, p5, p6, p8, p9, p10, p11, p12, p13, p14, p15, a1, a2, a3, a4, a5, a6, a7, b1, b2, b3, b4, b5, b6, b7, pf);
end while;
SELECT * FROM  temp;
 DROP TEMPORARY TABLE temp;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure View_Entry
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`View_Entry`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `View_Entry` ()
BEGIN
	
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure View_Patient_short
-- -----------------------------------------------------

USE `Exp_sys`;
DROP procedure IF EXISTS `Exp_sys`.`View_Patient_short`;

DELIMITER $$
USE `Exp_sys`$$
CREATE PROCEDURE `View_Patient_short` ()
BEGIN
declare length int default (SELECT COUNT(*) FROM patient_info);
declare n int default 0;
declare p1, p3 int;
declare p2 text;
declare dIn date;
CREATE temporary TABLE IF NOT EXISTS `temp`
(
	`id` INT ,
    `FIO` TEXT,
	`Age` INT
  );
loop1:while length >0
 Do
	SET length=length-1;
    SET n=n+1;
	Select `id`, `birth_date`,`FIO` into p1, dIn, p2 from patient_info where `id`=n;
    set p3=TIMESTAMPDIFF(YEAR, dIn, CURDATE());
	insert into temp values (p1, p2, p3);
end while;
SELECT * FROM  temp;
DROP TEMPORARY TABLE temp;
END
$$

DELIMITER ;
SET SQL_MODE = '';
GRANT USAGE ON *.* TO master;
 DROP USER master;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'master' IDENTIFIED BY '0000';

GRANT ALL ON `Exp_sys`.* TO 'master';
SET SQL_MODE = '';
GRANT USAGE ON *.* TO user;
 DROP USER user;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'user' IDENTIFIED BY '0000';

GRANT SELECT ON TABLE `Exp_sys`.* TO 'user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
