-- MySQL Script generated by MySQL Workbench
-- 10/29/15 02:00:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `default_schema` ;

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`diagnoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`diagnoses` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`diagnoses` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`anamnesis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`anamnesis` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`anamnesis` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` TEXT NULL COMMENT '',
  `complains` TEXT NULL COMMENT '',
  `description_sickness` TEXT NULL COMMENT '',
  `description_life` TEXT NULL COMMENT '',
  `Virus_deseases` TEXT NULL COMMENT '',
  `description_allergic` TEXT NULL COMMENT '',
  `State` TINYINT(1) NULL COMMENT '',
  `physique` TEXT NULL COMMENT '',
  `diet` TEXT NULL COMMENT '',
  `skin` TEXT NULL COMMENT '',
  `edema` TEXT NULL COMMENT '',
  `lymph nodes` TEXT NULL COMMENT '',
  `temperature` TEXT NULL COMMENT '',
  `respRate` TEXT NULL COMMENT '',
  `ChestVol` TEXT NULL COMMENT '',
  `percurative` TEXT NULL COMMENT '',
  `breathing` TEXT NULL COMMENT '',
  `heart_borders` TEXT NULL COMMENT '',
  `heart_tones` TEXT NULL COMMENT '',
  `artpressure` TEXT NULL COMMENT '',
  `heartRate` TEXT NULL COMMENT '',
  `pulse` TEXT NULL COMMENT '',
  `stomach` TEXT NULL COMMENT '',
  `liver` TEXT NULL COMMENT '',
  `Pastern` TEXT NULL COMMENT '',
  `stool` TEXT NULL COMMENT '',
  `urine` TEXT NULL COMMENT '',
  `PreDiagnosis_id` INT NULL COMMENT '',
  `Conclusion_compl` TEXT NULL COMMENT '',
  `conclusion_anamnesis` TEXT NULL COMMENT '',
  `research_plan` TEXT NULL COMMENT '',
  `treatment_plan` TEXT NULL COMMENT '',
  `disability` TEXT NULL COMMENT '',
  `doctor` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `diagnosis1_id_idx` (`PreDiagnosis_id` ASC)  COMMENT '',
  CONSTRAINT `preDiagnosis_id`
    FOREIGN KEY (`PreDiagnosis_id`)
    REFERENCES `default_schema`.`diagnoses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Adress` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Adress` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `region` TEXT NULL COMMENT '',
  `district` TEXT NULL COMMENT '',
  `City` TEXT NULL COMMENT '',
  `street` TEXT NULL COMMENT '',
  `house` TEXT NULL COMMENT '',
  `housing` TEXT NULL COMMENT '',
  `appartement` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`patient_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`patient_info` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`patient_info` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Sex` TINYINT(1) NULL COMMENT '',
  `Age` INT NULL COMMENT '',
  `diagnoses_id` INT NULL COMMENT '',
  `SNILS` INT NULL COMMENT '',
  `INN` INT NULL COMMENT '',
  `Passport_data` VARCHAR(500) NULL COMMENT '',
  `Info` VARCHAR(1000) NULL COMMENT '',
  `anamnesis_id` INT NULL COMMENT '',
  `FIO` TEXT NULL COMMENT '',
  `Insurance_number` TEXT NULL COMMENT '',
  `OGRN` TEXT NULL COMMENT '',
  `Insurance_firm` TEXT NULL COMMENT '',
  `card_number` TEXT NULL COMMENT '',
  `benefit_number` TEXT NULL COMMENT '',
  `adress_current_id` INT NULL COMMENT '',
  `adress_const_id` INT NULL COMMENT '',
  `birth_date` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `diagnosis_idx` (`diagnoses_id` ASC)  COMMENT '',
  INDEX `anamnesis_id_idx` (`anamnesis_id` ASC)  COMMENT '',
  INDEX `adress_curr_fk_idx` (`adress_current_id` ASC)  COMMENT '',
  INDEX `adress_const_fk_idx` (`adress_const_id` ASC)  COMMENT '',
  CONSTRAINT `diagnosis_fk`
    FOREIGN KEY (`diagnoses_id`)
    REFERENCES `default_schema`.`diagnoses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `anamnesis_id`
    FOREIGN KEY (`anamnesis_id`)
    REFERENCES `default_schema`.`anamnesis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `adress_curr_fk`
    FOREIGN KEY (`adress_current_id`)
    REFERENCES `default_schema`.`Adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `adress_const_fk`
    FOREIGN KEY (`adress_const_id`)
    REFERENCES `default_schema`.`Adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`dye_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`dye_type` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`dye_type` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`scope_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`scope_type` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`scope_type` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`entry` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`entry` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `about` VARCHAR(1000) NULL COMMENT '',
  `picture_ref` VARCHAR(100) NOT NULL COMMENT '',
  `patient_info_id` INT NULL COMMENT '',
  `scope_type_id` INT NULL COMMENT '',
  `dye_type_id` INT NULL COMMENT '',
  `zoom` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `patient_idx` (`patient_info_id` ASC)  COMMENT '',
  INDEX `dye_idx` (`dye_type_id` ASC)  COMMENT '',
  INDEX `scope_idx` (`scope_type_id` ASC)  COMMENT '',
  CONSTRAINT `patient_fk`
    FOREIGN KEY (`patient_info_id`)
    REFERENCES `default_schema`.`patient_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dye_fk`
    FOREIGN KEY (`dye_type_id`)
    REFERENCES `default_schema`.`dye_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scope_fk`
    FOREIGN KEY (`scope_type_id`)
    REFERENCES `default_schema`.`scope_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `default_schema`.`cond_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`cond_area` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`cond_area` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `description` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`TRadius`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`TRadius` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`TRadius` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `MaxRadius` FLOAT NULL COMMENT '',
  `MinRadius` FLOAT NULL COMMENT '',
  `AverageRadius` FLOAT NULL COMMENT '',
  `MeanSquareRadius` FLOAT NULL COMMENT '',
  `MaxRadiusPointX` POINT NULL COMMENT '',
  `MinRadiusPointX` POINT NULL COMMENT '',
  `InertiaMoment` FLOAT NULL COMMENT '',
  `RelInertiaMoment` FLOAT NULL COMMENT '',
  `Valid` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `TRadiuscol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`TFere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`TFere` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`TFere` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `MinDiametr` FLOAT NULL COMMENT '',
  `AngleMin` INT NULL COMMENT '',
  `CoupleMin1` POINT NULL COMMENT '',
  `CoupleMin2` POINT NULL COMMENT '',
  `MaxDiametr` FLOAT NULL COMMENT '',
  `AngleMax` INT NULL COMMENT '',
  `CoupleMax1` POINT NULL COMMENT '',
  `CoupleMax2` POINT NULL COMMENT '',
  `AverageDiametr` FLOAT NULL COMMENT '',
  `MeanSquareDiametr` FLOAT NULL COMMENT '',
  `Valid` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`morph_tthing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`morph_tthing` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`morph_tthing` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Min` POINT NULL COMMENT '',
  `Max` POINT NULL COMMENT '',
  `Spots` INT NULL COMMENT '',
  `SpotsSquare` INT NULL COMMENT '',
  `Start` POINT NULL COMMENT '',
  `ExtCircuit8Len` INT NULL COMMENT '',
  `ExtCircuit4Len` INT NULL COMMENT '',
  `ExtPerimetr` INT NULL COMMENT '',
  `IntCircuit8Len` INT NULL COMMENT '',
  `IntCircuit4Len` INT NULL COMMENT '',
  `IntPerimetr` INT NULL COMMENT '',
  `Square` INT NULL COMMENT '',
  `Fulness` FLOAT NULL COMMENT '',
  `ShapeFactor` FLOAT NULL COMMENT '',
  `Center` POINT NULL COMMENT '',
  `TRadius_id` INT NULL COMMENT '',
  `TFere_id` INT NULL COMMENT '',
  `ExtCircuitPoints` BLOB NULL COMMENT '',
  `IntCircuitPoints` BLOB NULL COMMENT '',
  `AllPoints` BLOB NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Tradius_idx` (`TRadius_id` ASC)  COMMENT '',
  INDEX `Tfere_idx` (`TFere_id` ASC)  COMMENT '',
  CONSTRAINT `Tradius_fk`
    FOREIGN KEY (`TRadius_id`)
    REFERENCES `default_schema`.`TRadius` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tfere_fk`
    FOREIGN KEY (`TFere_id`)
    REFERENCES `default_schema`.`TFere` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`mark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`mark` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`mark` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `entry_id` INT NOT NULL COMMENT '',
  `form` ENUM('rectangle', 'ellipse', 'polygon', 'arrow', 'nofigure') NULL DEFAULT NULL COMMENT '',
  `thickness` INT NULL COMMENT '',
  `cond_area_id` INT NULL COMMENT '',
  `name_id` INT NULL COMMENT '',
  `morph_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `entry_fk` (`entry_id` ASC)  COMMENT '',
  INDEX `diagnosis_idx` (`cond_area_id` ASC)  COMMENT '',
  INDEX `Morph_idx` (`morph_id` ASC)  COMMENT '',
  CONSTRAINT `entry_fk`
    FOREIGN KEY (`entry_id`)
    REFERENCES `default_schema`.`entry` (`id`),
  CONSTRAINT `cond_area_fk`
    FOREIGN KEY (`cond_area_id`)
    REFERENCES `default_schema`.`cond_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `morph_fk`
    FOREIGN KEY (`morph_id`)
    REFERENCES `default_schema`.`morph_tthing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `default_schema`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Users` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(45) NULL COMMENT '',
  `FirstName` VARCHAR(45) NULL COMMENT '',
  `LastName` VARCHAR(45) NULL COMMENT '',
  `type` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`journal` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`journal` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tableName` VARCHAR(45) NULL COMMENT '',
  `colName` VARCHAR(45) NULL COMMENT '',
  `rowId` INT NULL COMMENT '',
  `newValue` VARCHAR(1000) NULL COMMENT '',
  `Users_id` INT NULL COMMENT '',
  `Date` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `UserId_idx` (`Users_id` ASC)  COMMENT '',
  CONSTRAINT `UserId_fk`
    FOREIGN KEY (`Users_id`)
    REFERENCES `default_schema`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`mark_points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`mark_points` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`mark_points` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `point` POINT NULL COMMENT '',
  `mark_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `mark_id_idx` (`mark_id` ASC)  COMMENT '',
  CONSTRAINT `mark_id_fk`
    FOREIGN KEY (`mark_id`)
    REFERENCES `default_schema`.`mark` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Mark_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Mark_name` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Mark_name` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `color` INT NULL COMMENT '',
  `ParentId` INT NOT NULL DEFAULT -1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

USE `default_schema` ;

-- -----------------------------------------------------
-- procedure f_entryid_patientid
-- -----------------------------------------------------

USE `default_schema`;
DROP procedure IF EXISTS `default_schema`.`f_entryid_patientid`;

DELIMITER $$
USE `default_schema`$$
CREATE PROCEDURE `f_entryid_patientid` (in pat_id int)
BEGIN
		SELECT id FROM entry WHERE patient_info_id=(SELECT id  FROM patient_info WHERE id=pat_id);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sh_m_fullname
-- -----------------------------------------------------

USE `default_schema`;
DROP procedure IF EXISTS `default_schema`.`sh_m_fullname`;

DELIMITER $$
USE `default_schema`$$
CREATE PROCEDURE `sh_m_fullname` (in markid int, out markfeat varchar(100), out marktype varchar(100), out markname varchar(100) )
BEGIN
	SELECT name FROM mark_struct_type where id=(SELECT mark_struct_type_id FROM mark_struct_feature WHERE id=(SELECT mark_struct_feature_id FROM mark_name where id=markid)) INTO markfeat;
    SELECT name FROM mark_struct_feature WHERE id=(SELECT mark_struct_feature_id FROM mark_name where id=markid) INTO marktype;
    SELECT name FROM mark_name where id=markid INTO markname;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sh_m_type
-- -----------------------------------------------------

USE `default_schema`;
DROP procedure IF EXISTS `default_schema`.`sh_m_type`;

DELIMITER $$
USE `default_schema`$$
CREATE PROCEDURE `sh_m_type` ()
BEGIN

END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Anamnesys_pg1
-- -----------------------------------------------------

USE `default_schema`;
DROP procedure IF EXISTS `default_schema`.`Fill_Anamnesys_pg1`;

DELIMITER $$
USE `default_schema`$$
CREATE PROCEDURE `Fill_Anamnesys_pg1` (in dateIn text, in complIn text, in SickIn text, in LifeIn text, in deseasIn text, in allergIn text)
BEGIN
If (SELECT COUNT(*) FROM anamnesis)=0 then
INSERT INTO `anamnesis` (`id`, `date`, `complains`, `description_sickness`, `description_life`, `Virus_deseases`, `description_allergic`) VALUES ('0', dateIn, complIn, SickIn, LifeIn, deseasIn, allergIn);
else 
INSERT INTO `anamnesis` (`date`, `complains`, `description_sickness`, `description_life`, `Virus_deseases`, `description_allergic`) VALUES (dateIn, complIn, SickIn, LifeIn, deseasIn, allergIn);
end if;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Anamnesys_pg2
-- -----------------------------------------------------

USE `default_schema`;
DROP procedure IF EXISTS `default_schema`.`Fill_Anamnesys_pg2`;

DELIMITER $$
USE `default_schema`$$
CREATE PROCEDURE `Fill_Anamnesys_pg2` (in StateIn bool, in  PhysIn text, in  DietIn text, in  skinIn text, in  edemIn text, in  lymphIn text, in  tempIn text, in  respIn text, in  ChestIn text, in  PercurIn text, in  BreathIn text)
BEGIN
declare r int;
set r =(Select COUNT(*) from anamnesis);
update anamnesis
	set 
    `State`= StateIn,
    `physique` = PhysIn,
    `diet`= DietIn,
    `skin`= skinIn,
    `edema`= edemIn,
    `lymph nodes` = lymphIn,
    `temperature` = tempIn,
    `respRate` = respIn,
    `ChestVol` = ChestIn,
    `percurative` = PercurIn,
    `breathing` = BreathIn
    where id = r;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Anamnesys_pg3
-- -----------------------------------------------------

USE `default_schema`;
DROP procedure IF EXISTS `default_schema`.`Fill_Anamnesys_pg3`;

DELIMITER $$
USE `default_schema`$$
CREATE PROCEDURE `Fill_Anamnesys_pg3` (in HeartBorIn text, in  HeartTonIn text, in  ArtPresIn text, in  HeartRateIn text, in  PulseIn text, in  StomachIn text, in  liverIn text, in  PasternIn text, in  stoolIn text, in  urineIn text)
BEGIN
declare r int;
set r =(Select COUNT(*) from anamnesis);
update anamnesis
	set
	`heart_borders` = HeartBorIn,
    `heart_tones` = HeartTonIn,
    `artpressure` =  ArtPresIn,
    `heartRate` = HeartRateIn,
    `pulse` = PulseIn,
    `stomach` = StomachIn,
    `liver` = liverIn,
    `Pastern` = PasternIn,
    `stool` = stoolIn,
    `urine` = urineIn
    where id = r;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Anamnesys_pg4
-- -----------------------------------------------------

USE `default_schema`;
DROP procedure IF EXISTS `default_schema`.`Fill_Anamnesys_pg4`;

DELIMITER $$
USE `default_schema`$$
CREATE PROCEDURE `Fill_Anamnesys_pg4` (in PreDiag int, in  complIn text, in  anamnIn text, in  researchIn text, in  treatmIn text, in  DisabilIn text, in  DoctIn text)
BEGIN
declare r int;
set r =(Select COUNT(*) from anamnesis);
if (Select COUNT(id) FROM diagnoses where id=PreDiag)=0 then
set PreDiag=Null;
else set PreDiag=PreDiag;
end if;
update anamnesis
	set
	`PreDiagnosis_id` = preDiag,
    `Conclusion_compl` = complIn,
    `conclusion_anamnesis` = anamnIn,
    `research_plan` = researchIn,
    `treatment_plan` = treatmIn,
    `disability` = DisabilIn,
    `doctor` = DoctIn
    where id = r;
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Fill_Diag
-- -----------------------------------------------------

USE `default_schema`;
DROP procedure IF EXISTS `default_schema`.`Fill_Diag`;

DELIMITER $$
USE `default_schema`$$
CREATE PROCEDURE `Fill_Diag` (in idIn int, in NameIn varchar(100), in DescriptIn varchar(1000))
BEGIN
	INSERT INTO `default_schema`.`diagnoses` (`id`, `name`, `description`) VALUES (idIn, NameIn, DescriptIn);
END
$$

DELIMITER ;
SET SQL_MODE = '';
GRANT USAGE ON *.* TO master;
 DROP USER master;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'master' IDENTIFIED BY '0000';

GRANT ALL ON `default_schema`.* TO 'master';
SET SQL_MODE = '';
GRANT USAGE ON *.* TO user;
 DROP USER user;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'user' IDENTIFIED BY '0000';

GRANT SELECT ON TABLE `default_schema`.* TO 'user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
